blank_issues_enabled: false
contact_links:
  - name: 🎮 Pyrewarden website
    url: https://morass.github.io/pyrewarden/
    about: Game info, trailer, screenshots
  - name: 🛒 Pyrewarden on Steam
    url: https://store.steampowered.com/app/4774690/Pyrewarden/
    about: Store page, reviews, discussions
  - name: 💬 Discord
    url: https://discord.gg/KTKarn46yq
    about: Ask a question or chat with the community
